// Generated by CoffeeScript 1.4.0
(function() {
  var S3CP, Sync, async, knox, toarray;

  knox = require("knox");

  Sync = require("./sync");

  async = require("async");

  toarray = require("toarray");

  S3CP = (function() {
    /*
    */

    function S3CP(options) {
      this.options = options;
      this._s3 = knox.createClient(options);
    }

    /*
    */


    S3CP.prototype.download = function(options, callback) {
      return this._run("download", options, callback);
    };

    /*
    */


    S3CP.prototype.redownload = function(options, callback) {
      return this._run("redownload", options, callback);
    };

    /*
    */


    S3CP.prototype.upload = function(options, callback) {
      return this._run("upload", options, callback);
    };

    /*
    */


    S3CP.prototype._run = function(command, options, callback) {
      var _this = this;
      return async.eachSeries(toarray(options), (function(option, next) {
        var sync;
        sync = new Sync(_this, option);
        return sync.start(function() {
          return sync[command].call(sync, next);
        });
      }), callback);
    };

    return S3CP;

  })();

  module.exports = function(options) {
    return new S3CP(options);
  };

}).call(this);
