// Generated by CoffeeScript 1.4.0
(function() {
  var S3CP, Sync, async, knox, toarray;

  knox = require("knox");

  Sync = require("./sync");

  async = require("async");

  toarray = require("toarray");

  S3CP = (function() {
    /*
    */

    function S3CP(options) {
      this.options = options;
      this._s3 = knox.createClient(options);
    }

    /*
    */


    S3CP.prototype.sync = function(options, callback) {
      return new Sync(this, options).start(callback);
    };

    return S3CP;

  })();

  module.exports = function(options) {
    return new S3CP(options);
  };

}).call(this);
